# Generated by Django 4.1.3 on 2022-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_dicount_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
